import { Router } from 'express';
import authRoutes from './auth';
import contentRoutes from './content';
import creatorRoutes from './creators';
import subscriptionRoutes from './subscriptions';
import adminRoutes from './admin';
import notificationRoutes from './notifications';
import dashboardRoutes from './dashboard';
import pollRoutes from './polls';
import partnerRoutes from './partners';
import shopRoutes from './shop';
import albumRoutes from './albums';
import playlistRoutes from './playlists';
import seriesRoutes from './series';
import pushRoutes from './push';
import liveRoutes from './live';
import internalRoutes from './internal';
import { getPublicCss, getPublicSettings } from '../controllers/settings.controller';
import { listPublicBanners } from '../controllers/banner.controller';
import { unifiedSearch } from '../controllers/search.controller';
import { searchLimiter, readLimiter } from '../middleware/rateLimiter';
import { optionalAuthMiddleware } from '../middleware/auth';

export const router = Router();

router.use('/auth', authRoutes);
router.use('/content', contentRoutes);
router.use('/creators', creatorRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/admin', adminRoutes);
router.use('/notifications', notificationRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/polls', pollRoutes);
router.use('/partners', partnerRoutes);
router.use('/shop', shopRoutes);
router.use('/albums', albumRoutes);
router.use('/playlists', playlistRoutes);
router.use('/series', seriesRoutes);
router.use('/push', pushRoutes);
router.use('/live', liveRoutes);
router.use('/internal', internalRoutes);
router.get('/search', optionalAuthMiddleware, searchLimiter, unifiedSearch);
router.get('/site-settings/css', getPublicCss);
router.get('/site-settings/public', getPublicSettings);
router.get('/banners', readLimiter, listPublicBanners);
